package com.ecodrive.app.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity representing a driving trip stored in the local database.
 * Updated for universal approach (phone sensors + Smartcar API + optional OBD).
 */
@Entity(tableName = "trips")
data class TripEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val vehicleId: Long = 0,
    val startTimeEpochMs: Long = 0,
    val endTimeEpochMs: Long? = null,
    val distanceKm: Double = 0.0,
    val durationSeconds: Long = 0,
    val averageSpeedKmh: Double = 0.0,
    val maxSpeedKmh: Double = 0.0,
    val fuelConsumedLiters: Double = 0.0,
    val fuelEfficiencyLPer100Km: Double = 0.0,
    val ecoScore: Int = 0,
    val hardBrakeCount: Int = 0,
    val hardAccelCount: Int = 0,
    val sharpTurnCount: Int = 0,
    val idleTimeSeconds: Long = 0,
    val isActive: Boolean = true,
    // Smartcar API fuel calibration data
    val startFuelPercent: Double? = null,
    val endFuelPercent: Double? = null,
    val calibrationFactor: Double = 1.0,
    // Data source used for this trip
    val dataSource: String = "SENSORS", // SENSORS, OBD, HYBRID
)

/**
 * Room entity representing a driving event within a trip.
 */
@Entity(tableName = "driving_events")
data class DrivingEventEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val tripId: Long,
    val timestampEpochMs: Long,
    val type: String,        // DrivingEventType enum name
    val value: Double = 0.0,
    val speedAtEvent: Double = 0.0,
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val description: String = "",
)

/**
 * Room entity for storing raw data points at intervals during a trip.
 * Used for charting and detailed post-trip analysis.
 * Updated for sensor-based data collection.
 */
@Entity(tableName = "data_points")
data class DataPointEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val tripId: Long,
    val timestampEpochMs: Long,
    // GPS data
    val speedKmh: Double = 0.0,
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val altitudeM: Double = 0.0,
    // Accelerometer data
    val longitudinalAccelMps2: Double = 0.0,
    val lateralAccelMps2: Double = 0.0,
    // Derived
    val fuelRateEstimateLPerH: Double = 0.0,
    val fuelConsumptionLPer100Km: Double = 0.0,
    val roadGradePercent: Double = 0.0,
    // OBD data (optional, null when using sensors only)
    val rpm: Int? = null,
    val throttlePercent: Double? = null,
    val engineLoadPercent: Double? = null,
)

/**
 * Room entity for storing vehicle profile information.
 * Generalized for any vehicle model and fuel type.
 */
@Entity(tableName = "vehicles")
data class VehicleEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String = "My Vehicle",
    val make: String = "",
    val model: String = "",
    val year: Int = 2024,
    val vehicleType: String = "ICE",     // VehicleType enum name
    val fuelType: String = "GASOLINE", // FuelType enum name
    val massKg: Double = 1500.0,
    val dragCoefficient: Double = 0.3,
    val frontalAreaM2: Double = 2.2,
    val rollingResistance: Double = 0.012,
    val tankCapacityLiters: Double = 50.0,
    val engineDisplacementCc: Int = 2000,
    val fuelCalibrationFactor: Double = 1.0,
    val isDefault: Boolean = false,
)

/**
 * Room entity for fuel calibration history.
 * Stores comparison between estimated and actual fuel consumption
 * for self-improving the VSP model.
 */
@Entity(tableName = "fuel_calibration")
data class FuelCalibrationEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val tripId: Long,
    val estimatedFuelLiters: Double,
    val actualFuelLiters: Double,
    val distanceKm: Double,
    val correctionRatio: Double,
    val timestampEpochMs: Long,
)

/**
 * Room entity for caching AI-generated trip insights.
 *
 * Persisting insights means:
 * - Users can read them offline without re-querying Gemini.
 * - No duplicate API calls when navigating back to the same trip.
 * - One row per trip (tripId is unique); upserted on each regeneration.
 */
@Entity(tableName = "ai_insights", indices = [androidx.room.Index(value = ["tripId"], unique = true)])
data class AiInsightEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    /** The trip this insight belongs to. */
    val tripId: Long,
    /** Full AI-generated insight text (may be multi-paragraph). */
    val insightText: String,
    /** Whether this insight was generated by Gemini (true) or LocalEcoCoach fallback (false). */
    val isAiGenerated: Boolean,
    /** Epoch ms when this insight was generated. Used to decide if re-generation is needed. */
    val generatedAtEpochMs: Long = System.currentTimeMillis(),
    /** Model version used — helps detect stale insights after model upgrades. */
    val modelVersion: String = "gemini-2.0-flash",
)

/**
 * Room entity for an AI-generated driving challenge.
 * One active challenge at a time; completed challenges are archived.
 */
@Entity(tableName = "challenges")
data class ChallengeEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    /** Short display title (e.g., "Smooth Stopper"). */
    val title: String,
    /** Full description of the goal. */
    val description: String,
    /** Target count to reach (e.g., 0 hard brakes in 3 trips). */
    val targetCount: Int,
    /** Current progress count. */
    val progressCount: Int = 0,
    /** The DrivingEventType name this challenge targets (e.g., "HARD_BRAKE"). */
    val metricType: String,
    /** Duration in days the challenge is active. */
    val durationDays: Int = 7,
    val createdAtEpochMs: Long = System.currentTimeMillis(),
    val completedAtEpochMs: Long? = null,
    val isCompleted: Boolean = false,
    /** Badge type awarded on completion. */
    val rewardBadgeType: String? = null,
)

/**
 * Room entity for a badge earned by the driver.
 */
@Entity(tableName = "badges")
data class BadgeEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    /** BadgeType enum name. */
    val type: String,
    val title: String,
    val description: String,
    val earnedAtEpochMs: Long = System.currentTimeMillis(),
    /** Emoji icon for the badge. */
    val icon: String = "🏅",
)

/**
 * Room entity for a detected vehicle anomaly.
 */
@Entity(tableName = "anomalies")
data class AnomalyEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val tripId: Long,
    val type: String,
    val severity: String,
    val description: String,
    val detectedAtSpeedKmh: Double,
    val aiDiagnosis: String?,
)
